### ISSUE TITLE
automatically use virtualenv when using devcontainer

### ISSUE THREAD

**Issue by pascal456** [fhdw-forschung/modelling-tools#90]
# problem

- virtual environment is not activated consistently in all setups
- this problem also holds true for the bebefam project definition
- chances are that the problem is only with my machine

# details

- installation is done in folder `.venv`
- on some machines the env is activated (denoted by `(.venv)`)
- on some machines the env is not activated
- when manually activated the env is denoted by `(fhdw-modelling-py3.11)`

**Comment by pascal456** [comment]
@SLebs1 @mfueller 
kann mir einer von euch bitte einmal eure Variante der verschiedenen `settings.json` vom vscode hier hochladen?
es gibt drei verschiedene scopes dafür:
- default
- user (sync über alle geräte, wenn aktiviert)
- (remote-) machine
- workspace

ich vermute, dass irgendwo bei mir die config kaputt ist; das würde ich dann bei gelegenheit einmal auseinanderklamüsern und das dann auch für die devcontainer config festschreiben.

man kommt da jeweils über ein kommando ran:
![Image](https://github.com/fhdw-forschung/modelling-tools/assets/21061035/4024dacb-7f1f-4572-a6bd-8c8a6137fb84)

**Comment by mfueller** [comment]
hier meine default und user settings.
Beim Versuch die anderen beiden Settings zu öffnen bekomme ich einen Fehler, dass kein file system provider gefunden werden kann. Keine Ahnung was dies bedeutet...

[defaultSettings.json](https://github.com/fhdw-forschung/modelling-tools/files/13942999/defaultSettings.json)
[userSettings.json](https://github.com/fhdw-forschung/modelling-tools/files/13943000/userSettings.json)

**Comment by pascal456** [comment]
jo besten dank!

> hier meine default und user settings. Beim Versuch die anderen beiden Settings zu öffnen bekomme ich einen Fehler, dass kein file system provider gefunden werden kann. Keine Ahnung was dies bedeutet...

Wahrscheinlich weil die dateien nicht vorhanden sind, wäre normal, wenn du nichts geändert hast.

**Comment by pascal456** [comment]
Problem äußerte sich nur auf meiner Maschine. Es scheint für meinen User entsprechend konfiguriert zu sein; das sehe ich daran, dass es auch auf anderen Maschinen (aber selber Github Account) der Fall ist.

Würde ich für jetzt ignorieren, ist nur eine optische Sache.
